### ISSUE TITLE
Crashes during generation due to Global optionset on alternate key

### ISSUE THREAD

**Issue by rajyraman** [delegateas/XrmContext#29]
The generation of classes is not successful in D365 online. I get an error during generation.  It happens for solutioncomponentattributeconfiguration entity. It has an alternate key that is a global optionset.

Stack Trace
```
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at DG.XrmContext.CodeDomHelper.getAltKeyVarType(XrmAttributeType _arg1) in C:\GitHub\XrmContext\src\XrmContext\CodeDom\CodeDomHelper.fs:line 129
   at DG.XrmContext.XrmCodeDom.MakeEntityAltKeyRetrieve@197.Invoke(Tuple`3 tupledArg) in C:\GitHub\XrmContext\src\XrmContext\CodeDom\XrmCodeDom.fs:line 198
   at DG.XrmContext.XrmCodeDom.MakeEntityAltKeyRetrieve(String entityName, XrmAlternateKey altKey) in C:\GitHub\XrmContext\src\XrmContext\CodeDom\XrmCodeDom.fs:line 197
   at DG.XrmContext.XrmCodeDom.MakeEntity@312-2.Invoke(FSharpList`1 keys, XrmAlternateKey k) in C:\GitHub\XrmContext\src\XrmContext\CodeDom\XrmCodeDom.fs:line 313
   at Microsoft.FSharp.Collections.ArrayModule.Fold[T,TState](FSharpFunc`2 folder, TState state, T[] array) in E:\A\_work\130\s\src\fsharp\FSharp.Core\array.fs:line 899
   at DG.XrmContext.XrmCodeDom.MakeEntity(XrmEntity entity) in C:\GitHub\XrmContext\src\XrmContext\CodeDom\XrmCodeDom.fs:line 309
   at DG.XrmContext.XrmCodeDom.MakeCodeUnit@420.Invoke(XrmEntity entity) in C:\GitHub\XrmContext\src\XrmContext\CodeDom\XrmCodeDom.fs:line 420
   at DG.XrmContext.XrmCodeDom.MakeCodeUnit(XrmEntity[] entities, Tuple`2[] intersects, String ns, FSharpOption`1 context) in C:\GitHub\XrmContext\src\XrmContext\CodeDom\XrmCodeDom.fs:line 420
   at DG.XrmContext.FileGeneration.createSingleFileCodeDom(InterpretedState state) in C:\GitHub\XrmContext\src\XrmContext\Generation\FileGeneration.fs:line 70
   at DG.XrmContext.GenerationMain.generateFromRaw(XcGenerationSettings gSettings, RawState rawState) in C:\GitHub\XrmContext\src\XrmContext\Generation\GenerationMain.fs:line 31
   at DG.XrmContext.XrmContext.GenerateFromCrm(XrmAuthentication xrmAuth, XcRetrievalSettings rSettings, XcGenerationSettings gSettings) in C:\GitHub\XrmContext\src\XrmContext\XrmContext.fs:line 49
   at Program.connectGen(FSharpMap`2 parsedArgs) in C:\GitHub\XrmContext\src\XrmContext\CommandLine\Program.fs:line 94
   at Program.executeWithArgs(FSharpList`1 argv) in C:\GitHub\XrmContext\src\XrmContext\CommandLine\Program.fs:line 115
   at Program.main(String[] argv) in C:\GitHub\XrmContext\src\XrmContext\CommandLine\Program.fs:line 122
```
![image](https://user-images.githubusercontent.com/5035266/72859868-54899180-3d19-11ea-945c-6c6db4ab591c.png)
![image](https://user-images.githubusercontent.com/5035266/72859879-58b5af00-3d19-11ea-80c6-cfdb26ac08da.png)
![image](https://user-images.githubusercontent.com/5035266/72859882-5c493600-3d19-11ea-9185-c0d9f89e0d9c.png)

**Comment by magesoe** [comment]
This is of course an error, but what are you using this entity for?

**Comment by magesoe** [comment]
Added in 1.7.2
